export const ROOMS_LOADING = 'ROOMS_LOADING';
export const ROOMS_FAILED = 'ROOMS_FAILED';
export const ADD_ROOMS = 'ADD_ROOMS';

export const POST_RESERVATION = 'POST_RESERVATION';
export const ADD_ALL_RESERVATION = 'ADD_ALL_RESERVATION';
export const ALL_RESERVATION_FAILED = 'ALL_RESERVATION_FAILED';